import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/navbar";
import { getCurrentSession } from "@/actions/cookies";
import UserAuthProvider from "@/components/providers/UserStoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getCurrentSession();

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <UserAuthProvider user={user || null}>
          <Navbar />
          {children}
        </UserAuthProvider>
      </body>
    </html>
  );
}
