version: "3.8"
services:
  next:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
      - "24678:24678" # Turbopack HMR
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/.next/cache
      - /app/.turbo
    environment:
      - NODE_ENV=development
      - TURBOPACK_POLLING_INTERVAL=2000
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
